wandb_version: 1

lr:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: resnet50_multiple_fc_example
dataset:
  desc: null
  value: given
epochs:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712493198.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.16.5
      8:
      - 1
      - 5
      13: linux-x86_64
